spring:
  profiles:
    active:
      - test
    group:
      local:
        - mysql
        - security
        - aws
        - redis
        - web
      test:
        - h2
        - security
        - aws
        - redis
        - web
      prod:
        - mysql
        - security
        - aws
        - redis
        - web
